dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install nbfancy

script:
  - nbfancy configure -y all_magic
  - nbfancy init --include none
  - nbfancy render
  - nbfancy html
  - jupyter nbconvert nbfancy/slides.ipynb --to slides
  - mv slides.slides.html html/index.html

deploy:
  provider: pages
  repo: JDBetteridge/nbfancy
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7

